# Generated by Django 3.1 on 2020-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mekan', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='country', max_length=100),
            preserve_default=False,
        ),
    ]
